application: inwestuj-w-firmy
version: 201402262029
runtime: java

static_files:
  - include: /en/**
  - include: /pl/**
  - include: /**.ico
  - include: /**.txt
  - include: /crossdomain.xml
  - include: /*
    expiration: 10m

handlers:
  - url: /hello/*
    servlet: eu.finwest.web.servlets.HelloServlet
  - url: /setup/*
    servlet: eu.finwest.web.servlets.SetupServlet
  - url: /payment/*
    servlet: eu.finwest.web.servlets.PaymentsServlet
  - url: /twitter_login
    servlet: eu.finwest.web.servlets.TwitterLoginServlet
  - url: /twitter_logout
    servlet: eu.finwest.web.servlets.TwitterLogoutServlet
  - url: /twitter_callback
    servlet: eu.finwest.web.servlets.TwitterCallbackServlet
  - url: /facebook_login
    servlet: eu.finwest.web.servlets.FacebookLoginServlet
  - url: /facebook_logout
    servlet: eu.finwest.web.servlets.FacebookLogoutServlet
  - url: /facebook_callback
    servlet: eu.finwest.web.servlets.FacebookCallbackServlet
  - url: /*
    servlet: eu.finwest.web.FrontController
  - url: /remote_api
    servlet: com.google.apphosting.utils.remoteapi.RemoteApiServlet

listeners:
   - eu.finwest.web.servlets.WarmupListener

welcome_files:
  - discover-page.html

inbound_services:
  - warmup

admin_console:
  pages:
  - name: InwestujWFirmy Test Page
    url: /hello
  - name: InwestujWFirmy Setup Page
    url: /setup

sessions_enabled: true

threadsafe: true

error_handlers:
  - file: error-page.html

  - error_code: over_quota
    file: error-page.html

  - error_code: dos_api_denial
    file: error-page.html

  - error_code: timeout
    file: error-page.html

admin_console:
  pages:
  - name: Setup Config
    url: /setup
  - name: Hello Test Page
    url: /hello

system_properties:
  com.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize: true
  java.awt.headless: true

